/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BusavaTragaRouteImport } from './routes/busava-traga'
import { Route as IndexRouteImport } from './routes/index'

const BusavaTragaRoute = BusavaTragaRouteImport.update({
  id: '/busava-traga',
  path: '/busava-traga',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busava-traga': typeof BusavaTragaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busava-traga': typeof BusavaTragaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busava-traga': typeof BusavaTragaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/busava-traga'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/busava-traga'
  id: '__root__' | '/' | '/busava-traga'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusavaTragaRoute: typeof BusavaTragaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/busava-traga': {
      id: '/busava-traga'
      path: '/busava-traga'
      fullPath: '/busava-traga'
      preLoaderRoute: typeof BusavaTragaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusavaTragaRoute: BusavaTragaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
